### ISSUE TITLE
When adding as CMake subdirectory adds many extra projects

### ISSUE THREAD

**Issue by adishavit** [nonstd-lite/expected-lite#12]
When I put this repo as a submodule, I can of course include just the header file.
However, how can I use this as a library dependency without getting all the test projects into my build?

**Comment by martinmoene** [comment]
I [plan to provide CMake packages](https://github.com/martinmoene/nonstd-lite/blob/master/plan/08-plan-build-cmake.txt) for the *nonstd lite* projects as with [*gsl lite*](https://github.com/martinmoene/gsl-lite/blob/master/CMakeLists.txt), which I hope is an answer to your problem. However, there's only so much one can do...

**Comment by adishavit** [comment]
Never used them.
But span-lite works well with no superfluous projects.

**Comment by martinmoene** [comment]
ok thanks, that'll be a change I can do quite quickly.

**Comment by martinmoene** [comment]
... done.

**Comment by adishavit** [comment]
Fantastic!
