### ISSUE TITLE
How to get exception type

### ISSUE THREAD

**Issue by feedhandler** [nonstd-lite/expected-lite#13]
Hi, 
nice library. This is a usage question rather than a bug or issue:
When using the checked value accessor the class throws an exception if there is no value. Is there an easy way to get the type of the exception? e.g. see below, is there a cleaner way to write the type in the catch statement? 

```c++
#include "expected.hpp"
#include <iostream>
#include <string>

int main()
{
  nonstd::expected<int, std::string> e{ nonstd::unexpect, "something went wrong" };
  
  try
  {
    e.value();
  }
  catch (nonstd::bad_expected_access<std::string> x) // is there a cleaner way to write this?
  {
    std::cout << "what: " << x.what() << std::endl;
    std::cout << "error: " << x.error() << std::endl;
  }
}
```
Thanks

**Comment by martinmoene** [comment]
I don't know of a clearer way to write it other than defining aliases that use domain-related names.

**Comment by feedhandler** [comment]
OK, thanks.
So is there no way to get the exception type from the object? It would be nice to avoid having to know that the bad_expected_access is templated on string. Something like 
```c++
try
  {
    e.value();
  }
  catch (e.exception_type x) // this is the kind of thing I was hoping for...
  {
  ...
```

**Comment by martinmoene** [comment]
As far as I can see, something like this is not in the [proposal p0323](http://wg21.link/p0323) for `std::expected`, which expected-lite tries to follow.

**Comment by feedhandler** [comment]
OK no problem. I was just checking I hadn't missed something. Thanks anyway
