### ISSUE TITLE
can't work with optional-lite because of nonstd::in_place_t

### ISSUE THREAD

**Issue by lethe555** [nonstd-lite/expected-lite#14]

**Comment by martinmoene** [comment]
Is there any thing you *expect* from me?

**Comment by lethe555** [comment]
I'm using vs2017 for now ,in optional-lite there is `nonstd{ using std::in_place; }`
in expected-lite there is `nonstd{ struct in_place_t{}; constexpr in_place_t in_place{};} ` 
maybe expected-lite can also using std::in_place

**Comment by martinmoene** [comment]
Edit: ^__ is about using `std::in_place` via namespace `nonstd`. Note to self: try and see.
___
Ah, (you mean that) the definitions with respect to `in_place` in `expected` have yet to be shared with `nonstd any`, `optional`, and `variant`, see [code of optional](https://github.com/martinmoene/optional-lite/blob/109541573bdae9c55d245be10d83bad96c6bd3d6/include/nonstd/optional.hpp#L275) and indication in [expected](https://github.com/martinmoene/expected-lite/blob/41f693a46a6e315273d2d46130f5e0b130e540d9/include/nonstd/expected.hpp#L524).

**Edit**: see *nonstd-lite* [issue 17](https://github.com/martinmoene/nonstd-lite/issues/17): Align in_place between any, expected, optional, variant.
