### ISSUE TITLE
Conan.io package

### ISSUE THREAD

**Issue by Manu343726** [nonstd-lite/expected-lite#21]
I would love if you submit a recipe for expected-lite to your conan repository, I need this for @flexferrum's Jinja2Cpp recipe

> Yes, this is a copy-paste from the variant-ptr-lite issue...

**Comment by martinmoene** [comment]
>>Yes, this is a copy-paste from the variant-ptr-lite issue...

Perhaps it is of [value_ptr-lite](https://github.com/martinmoene/value-ptr-lite/issues/4) ;)

I like to; It does require me to study conan (again) and find a form that makes sense to me...

**Comment by Manu343726** [comment]
Ah, I thought the nonstd repo (https://bintray.com/agauniyal/nonstd-lite) was yours. I will try to contact the author then.

**Comment by martinmoene** [comment]
I'll give it a try myself anyway.

**Comment by Manu343726** [comment]
FYI I'm writing recipes for your libraries [here](https://gitlab.com/Manu343726/conan-nonstdlite-packages)

**Comment by martinmoene** [comment]
@Manu343726 
Release [0.2.0:testing](https://bintray.com/martinmoene/nonstd-lite/expected-lite%3Anonstd-lite/0.2.0%3Atesting) on [expected-lite:nonstd-lite](https://bintray.com/martinmoene/nonstd-lite/expected-lite%3Anonstd-lite).

**Comment by martinmoene** [comment]
See: [expected-lite:nonstd-lite](https://bintray.com/martinmoene/nonstd-lite/expected-lite%3Anonstd-lite)

**Comment by martinmoene** [comment]
I think this one can be closed.
