### ISSUE TITLE
installation file structure

### ISSUE THREAD

**Issue by rmorozov** [nonstd-lite/expected-lite#25]
Hello @martinmoene !

I want to file one more small issue.

When you want to perform make install the resulting file structure contains include directory several times.

how to reproduce

git clone https://github.com/martinmoene/expected-lite.git

cd expected-lite
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install ../
make && make install

/Users/user/Source/expected-lite/build/install/include/include

that results in not working cmake config

I think you need to reconsider 

install(
    DIRECTORY   "${CMAKE_SOURCE_DIR}/include/"
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
)

please pay attention to trailing /  in "${CMAKE_SOURCE_DIR}/include/"

**Comment by martinmoene** [comment]
Thanks @rmorozov ,

I updated expected-lite, optional-lite, value_ptr-lite, variant-lite.

**Comment by martinmoene** [comment]
I think this one can be closed.
