### ISSUE TITLE
Static analysis complaint on const/non-const

### ISSUE THREAD

**Issue by dad4x** [nonstd-lite/expected-lite#28]
A static analysis tool reported the following:

In file included from terr.cpp:36:
include/nonstd/expected.hxx:1359:5: error: no type named 'type' 
in 'std::enable_if<false, nonstd::expected_lite::expected<int, ErrData> &>'
    nsel_REQUIRES_R(
    ^~~~~~~~~~~~~~~~
include/nonstd/expected.hxx:227:49: note: expanded from macro 'n
sel_REQUIRES_R'
    typename std::enable_if< (__VA_ARGS__), R>::type
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
include/nonstd/expected.hxx:722:39: error: the parameter for this explicitly-defaulted copy assignment operator is const, but a member or base requires it to be non-const
    nsel_constexpr14 unexpected_type& operator=( unexpected_type const & ) = default;

**Comment by martinmoene** [comment]
Can you provide a [minimal complete example](https://stackoverflow.com/help/mcve)?

**Comment by dad4x** [comment]
Nevermind, it was a broken change in the unexpected type.
