### ISSUE TITLE
Build example error 

### ISSUE THREAD

**Issue by crudine9** [nonstd-lite/expected-lite#29]
Hi,

with the flag -DEXPECTED_LITE_OPT_BUILD_EXAMPLES=ON the build (gcc-7) produces following error

`expected-lite/include/nonstd/expected.hpp: In instantiation of ‘class nonstd::expected_lite::expected<required<int>, char>’:

expected-lite/example/02-required.cpp:45:30:   required from here
expected-lite/include/nonstd/expected.hpp:1103:22: error: no type named ‘type’ in ‘struct std::enable_if<false, void*>’
     nsel_constexpr14 expected( expected const & other
                      ^~~~~~~~
expected-lite/include/nonstd/expected.hpp:1214:22: error: no type named ‘type’ in ‘struct std::enable_if<false, void*>’
     nsel_constexpr14 expected( value_type const & value
                      ^~~~~~~~
expected-lite/include/nonstd/expected.hpp:1378:5: error: no type named ‘type’ in ‘struct std::enable_if<false, nonstd::expected_lite::expected<required<int>, char>&>’
     operator=( expected const & other )
     ^~~~~~~~
expected-lite/include/nonstd/expected.hpp:1391:5: error: no type named ‘type’ in ‘struct std::enable_if<false, nonstd::expected_lite::expected<required<int>, char>&>’
     operator=( expected && other ) noexcept
     ^~~~~~~~
expected-lite/include/nonstd/expected.hpp:1469:5: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
     swap( expected & other ) noexcept
     ^~~~
`
Trying to use it in project produces also the same error. I don't understand what could be the problem.

**Comment by martinmoene** [comment]
Thanks @crudine9 , [example/02-required.cpp](https://github.com/martinmoene/expected-lite/blob/master/example/02-required.cpp) no longer compiles after changes to the implementation of `expected.hpp` to make it follow the proposal more strictly. I'll have to reconsider this example.

**Comment by martinmoene** [comment]
Think this can be closed.
