### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by martinzink** [nonstd-lite/expected-lite#44]
The latest release (v0.5.0) currently doesn't compile with the latest(v12.1.0) gcc with `-std=c++20`
This was fixed in #43, but it would be nice if there was a release that contains that fix.
Any plans for the next release?

**Comment by martinmoene** [comment]
Yes, hope to do a GitHub release later today. Thanks for the heads-up.

**Comment by martinmoene** [comment]
Just published release [v0.6.0](https://github.com/martinmoene/expected-lite/releases/tag/v0.6.0).

**Comment by martinzink** [comment]
thank you :+1:
