### ISSUE TITLE
Fix version number contained in files and Release as v0.6.1 (was: Update Conan recipe for v0.6.0)

### ISSUE THREAD

**Issue by martinmoene** [nonstd-lite/expected-lite#47]
Per PR #46

- [x] ~~Update~~ Make new GitHub Release tag.
- [x] Update Conan recipe: Create [PR](https://github.com/conan-io/conan-center-index/pull/11385).
- [x] Update Conan recipe: PR merged.

**Comment by striezel** [comment]
> Update GitHub Release tag

If that means that the old tag is deleted and another commit is tagged as v0.6.0, then be aware that this may cause some inconsistencies among existing forks and working copies of expected-lite. More details about why re-tagging can be problematic can be read in the official Git documentation: https://git-scm.com/docs/git-tag#_on_re_tagging

Bottom line is:

Git does not update tags in existing repositories when doing a `git fetch` or `git pull`. So anyone who has checked out the repository will still have the old v0.6.0 tag _unless the tag is updated manually in that person's repository checkout_. So it might be easier to just create a new tag (e. g. v0.6.1) and use that one instead, possibly pointing out that v0.6.0 has the wrong version in the code and should not be used anymore.

**Comment by martinmoene** [comment]
Thanks @striezel for your informed suggestion to do a/the sensible thing :)

**Comment by martinmoene** [comment]
Released [v0.6.1](https://github.com/martinmoene/expected-lite/releases/tag/v0.6.1) here and on [Conan Center](https://conan.io/center/expected-lite), closing issue.
