### ISSUE TITLE
Add `and_then`, `or_else`, `transform`, and `transform_error`.

### ISSUE THREAD

**Issue by BenFrantzDale** [nonstd-lite/expected-lite#56]
https://en.cppreference.com/w/cpp/utility/expected in C++23 will have those four member functions. We should have them in this `expected` library too.

**Comment by martinmoene** [comment]
thanks for the heads-up.

**Comment by martinmoene** [comment]
See proposal [p2505](http://wg21.link/p2505): Monadic Functions for `std::expected` by Jeff Garland.

**Comment by martinmoene** [comment]
Implemented by @szaszm in #60.
