### ISSUE TITLE
Use ``std::addressof`` instead of plain ``operator &``

### ISSUE THREAD

**Issue by DNKpp** [nonstd-lite/expected-lite#70]
I find myself often working with some ``COM``-like types, which I would like to wrap inside an ``expected``. Unfortunately, some of those types have an overloaded ``operator &`` which perform a cleanup (don't ask why...). In fact, this constantly crashes, because ``expected-lite`` performs a placement-new and requests the address via ``operator &`` which then leads to a cleanup of unitialized ptrs.
![image](https://github.com/user-attachments/assets/2a3702f8-4817-43ee-9947-9351ebacada9)

I think, using ``std::addressof`` instead of the plain ``operator &`` should help here.

**Comment by DNKpp** [comment]
@martinmoene thank you for the quick fix. Wouldn't it be beneficial to apply the same on the error object?

**Comment by martinmoene** [comment]
Ah, missed that, thanks.
